FROM mariadb:10.6.14

# Copy your custom configuration file
COPY my.cnf /etc/mysql/conf.d/

# Set environment variables (optional)
ENV MYSQL_ROOT_PASSWORD=ahmad123

# Expose the MariaDB port
EXPOSE 3306